FROM python:3.12-slim

WORKDIR /app

COPY requirements_worker.txt .

RUN pip install --no-cache-dir -r requirements_worker.txt

COPY . .

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
