"""Add conversation and message tables with clean indexing

Revision ID: 4a3374e096ac
Revises: 79513b721361
Create Date: 2025-07-06 19:22:26.489699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a3374e096ac'
down_revision: Union[str, Sequence[str], None] = '79513b721361'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_conversations_conversation_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_description'), table_name='conversations')
    op.drop_column('conversations', 'conversation_id')
    op.add_column('messages', sa.Column('message_type', sa.Enum('user', 'assistant', name='messagetype'), nullable=False))
    op.drop_index(op.f('ix_messages_content'), table_name='messages')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_messages_content'), 'messages', ['content'], unique=False)
    op.drop_column('messages', 'message_type')
    op.add_column('conversations', sa.Column('conversation_id', sa.INTEGER(), nullable=True))
    op.create_index(op.f('ix_conversations_description'), 'conversations', ['description'], unique=False)
    op.create_index(op.f('ix_conversations_conversation_id'), 'conversations', ['conversation_id'], unique=False)
    # ### end Alembic commands ###
